package.json
src/app/components/tabs/chart.service.ts
src/app/components/tabs/tabs.component.html
src/app/gapminder-tools.css
src/app/index.html
vizabi-copy-linux
vizabi-copy-mac
vizabi-copy-win.bat

feat(charts): add bar rank and line charts

---

src/app/components/tabs/chart.service.ts
src/app/components/tabs/tab.model.ts
src/app/header.css
src/app/index.html

The active tab closing cross: pointer on hover
add and apply Bariol font, like in ng2-tools-page
new tabs should be default-named by tools: Bubbles 1, Mountains 2, Bubbles 3
Closes #69 #70 #71

chore(ui): different ui improvements

---

src/app/app.component.html
src/app/app.component.ts
src/app/components/menu/hamburger-menu.component.html
src/app/components/menu/hamburger-menu.component.ts
src/app/components/menu/menu-actions.ts
src/app/components/menu/system-menu.ts
src/app/components/tabs-new/tab-title-edit.component.ts
src/app/components/tabs/chart.service.ts
src/app/electron.js
src/app/file-management.js

feat(general): save all tabs together as one config file

---

FileAssociation.nsh
build-win32.bat
build-win64.bat
dmg-builder/Info.plist
gapminder-offline.nsi
package.js
src/app/components/tabs/tabs.component.html
src/app/components/tabs/tabs.component.ts
src/app/electron.js
src/app/file-management.js
vizabi-copy-linux

feat(general): explore file extensions other than JSON

---

package.json
src/app/electron.js
src/app/package.json

chore(updating): Find a way to not drag along the stub versions forever

---

src/app/app.component.html
src/app/app.component.ts
src/app/components/ddf-dataset-config-form/ddf-dataset-config-form.component.ts
src/app/constants.ts

fixed(general): DDF folder dialog works correctly only once

---

src/app/app.component.html
src/app/app.component.ts
src/app/components/tabs-new/tabs.component.html
src/app/components/tabs-new/tabs.component.ts
src/app/components/tabs/tabs.component.html
src/app/components/tabs/tabs.component.ts
src/app/constants.ts
src/app/header.css

feat(tabs): Handle situation when too many tabs are opened

---

package-lock.json
package.json
src/app/components/csv-config-form/csv-config-form.component.html
src/app/components/csv-config-form/csv-config-form.component.ts
src/app/components/tabs/chart.service.ts

feat(chart processing): Add time format selector

---

src/app/file-management.js

fixed(ux): Fix a bug / Improve UX when a csv file has moved

---

package-lock.json
package.json
src/app/components/auto-update/auto-update.component.html
src/app/components/auto-update/auto-update.component.ts
src/app/electron.js
src/app/package.json

fixed(auto-update): unsuccessful updates from 2.1.0

---

src/app/app.module.ts
src/app/components/csv-config-form/csv-config-form.component.html
src/app/components/csv-config-form/csv-config-form.component.ts
src/app/components/smart-file-selector/smart-file-selector.component.css
src/app/components/smart-file-selector/smart-file-selector.component.html
src/app/components/smart-file-selector/smart-file-selector.component.ts

feat(general): redesign for file selector (csv form)

---

gapminder-offline.nsi

chore(install): Windows installer should automatically close on success

---

package-lock.json
package.json
src/app/app.component.ts
src/app/components/tabs/chart.service.ts

Next issues were resolved:
- open DDF folder: open one dataset, open another dataset
- open DDF folder: validate if it has datapackage.json
Closes #153 #154

fixed(general): chart behavior was fixed

---

package-lock.json
src/app/components/csv-config-form/csv-config-form.component.ts

When a valid path to CSV/DDF remains from the last file (like now) -- enable OK
Open CSV file in new tab
Open the same CSV file again in new tab, note that path to file is still in the dialog but OK is disabled
expected: if the path is valid we should be able to not pick the file again
Closes #167

chore(ui): save previous csv form state

---

src/app/electron.js

chore(general flow): Check running app duplicates on start

---

src/app/components/ddf-dataset-config-form/ddf-dataset-config-form.component.html
src/app/components/ddf-dataset-config-form/ddf-dataset-config-form.component.ts

chore(ui): Double error when no datapackage.json in DDF folder

---

src/app/components/tabs/tabs.component.ts
src/app/electron.js

fixed(ui): Windws 32bit version: no version info at the top

---

src/app/app.component.ts
src/app/components/csv-config-form/csv-config-form.component.ts
src/app/components/tabs/chart.service.ts

fixed(general flow): broke the app by opening a file twice in one chart

---

src/app/app.component.ts
src/app/components/menu/hamburger-menu.component.html
src/app/components/menu/menu-actions.ts
src/app/components/menu/system-menu.ts
src/app/svg-crowbar.js

feat(chart export): save current chart as SVG/PNG

---

src/app/components/tabs-new/tab-title-edit.component.ts

fixed(ui): Renaming tabs bug that removes some symbols while typing

---

src/app/components/tabs/tabs.component.ts

fixed(ui): Open all URLs in external window

---

src/app/components/menu/system-menu.ts

Copy-Paste supporting

---

src/app/components/menu/menu-actions.ts

fixed(chart export): all of the charts are merged during SVG/PNG export

---

src/app/components/auto-update/auto-update.component.html
src/app/components/auto-update/auto-update.component.ts
src/app/electron.js

chore(autoupdate): Add "if all else fails" message

---

package.json
src/app/components/file-select-config-form/file-select-config-form.component.css
src/app/components/file-select-config-form/file-select-config-form.component.html
src/app/components/file-select-config-form/file-select-config-form.component.ts
src/app/components/tabs/chart.service.ts

* Ability to add an extra column that describes full name of country to csv or xls file
Closes #244

feat(Data processing): name column feature was provided

---

src/app/components/tabs/tabs.component.ts

fixed(UI): error during tab closing

---

src/app/components/tabs-new/tabs.component.html
src/app/components/tabs-new/tabs.component.ts
src/app/components/tabs/tabs.component.ts
src/app/constants.ts
src/app/directives/vizabi.ts
src/app/message.service.ts

fixed(Vizabi integration): Chart content disappears
